fix: run go tests

diff --git a/.github/workflows/go-build.yml b/.github/workflows/go-build.yml
--- a/.github/workflows/go-build.yml
+++ b/.github/workflows/go-build.yml
@@ -27,6 +27,10 @@ jobs:
       run: sudo apt-get update && sudo apt-get install -y libpcap-dev
 
     - name: Build
-      run: go build 
+      run: |
+        go build -o arpmonitor
+        test -s arpmonitor || (echo "❌ Build failed: arpmonitor binary missing or empty" && exit 1)
     - name: Test
+      working-directory: ${{ github.workspace }}
       run: go test -v ./...
+
